import itk


def DWI_BSplines(*argv):
    parameter_object = itk.ParameterObject.New()
    parameter_map_bspline = parameter_object.GetDefaultParameterMap('bspline')
    parameter_object.AddParameterMap(parameter_map_bspline)
    parameter_object.SetParameter("FixedInternalImagePixelType", "float")
    parameter_object.SetParameter("MovingInternalImagePixelType", "float")
    parameter_object.SetParameter("FixedImageDimension", "2")
    parameter_object.SetParameter("MovingImageDimension", "2")
    parameter_object.SetParameter("UseDirectionCosines", "true")
    parameter_object.SetParameter("Registration", "MultiResolutionRegistration")
    parameter_object.SetParameter("ImageSampler", "RandomCoordinate")
    parameter_object.SetParameter("Interpolator", "BSplineInterpolator")
    parameter_object.SetParameter("ResampleInterpolator", "FinalBSplineInterpolator")
    parameter_object.SetParameter("Resampler", "DefaultResampler")
    parameter_object.SetParameter("BSplineInterpolationOrder", "1")
    parameter_object.SetParameter("FinalBSplineInterpolationOrder", "1")
    parameter_object.SetParameter("FixedImagePyramid", "FixedSmoothingImagePyramid")
    parameter_object.SetParameter("MovingImagePyramid", "MovingSmoothingImagePyramid")
    parameter_object.SetParameter("Optimizer", "AdaptiveStochasticGradientDescent")
    parameter_object.SetParameter("HowToCombineTransforms", "Compose")
    parameter_object.SetParameter("Transform", "BSplineTransform")
    parameter_object.SetParameter("Metric", "AdvancedMeanSquares")
    parameter_object.SetParameter("NumberOfHistogramBins", "32")
    parameter_object.SetParameter("FinalGridSpacingInPhysicalUnits", "50.0 50.0")
    parameter_object.SetParameter("NumberOfResolutions", "4")
    parameter_object.SetParameter("AutomaticParameterEstimation", "true")
    parameter_object.SetParameter("ASGDParameterEstimationMethod", "Original")
    parameter_object.SetParameter("MaximumNumberOfIterations", "500")
    parameter_object.SetParameter("MaximumStepLength", "0.1")
    parameter_object.SetParameter("ImagePyramidSchedule", "8 8  4 4  2 2  1 1")
    parameter_object.SetParameter("NumberOfSpatialSamples", "2048")
    parameter_object.SetParameter("NewSamplesEveryIteration", "true")
    parameter_object.SetParameter("CheckNumberOfSamples", "true")
    parameter_object.SetParameter("ErodeFixedMask", "false")
    parameter_object.SetParameter("DefaultPixelValue", "0")
    parameter_object.SetParameter("WriteResultImage", "true")
    parameter_object.SetParameter("ResultImagePixelType", "float")
    parameter_object.SetParameter("ResultImageFormat", "mhd")
    for list_parameters in argv:
        parameter_object.SetParameter(str(list_parameters[0]), str(list_parameters[1]))
    return parameter_object

def T1_BSplines(*argv):
    parameter_object = itk.ParameterObject.New()
    parameter_map_bspline = parameter_object.GetDefaultParameterMap('bspline')
    parameter_object.AddParameterMap(parameter_map_bspline)
    parameter_object.SetParameter("FixedInternalImagePixelType", "float")
    parameter_object.SetParameter("MovingInternalImagePixelType", "float")
    parameter_object.SetParameter("FixedImageDimension", "2")
    parameter_object.SetParameter("MovingImageDimension", "2")
    parameter_object.SetParameter("UseDirectionCosines", "true")
    parameter_object.SetParameter("Registration", "MultiResolutionRegistration")
    parameter_object.SetParameter("ImageSampler", "RandomCoordinate")
    parameter_object.SetParameter("Interpolator", "BSplineInterpolator")
    parameter_object.SetParameter("ResampleInterpolator", "FinalBSplineInterpolator")
    parameter_object.SetParameter("Resampler", "DefaultResampler")
    parameter_object.SetParameter("BSplineInterpolationOrder", "1")
    parameter_object.SetParameter("FinalBSplineInterpolationOrder", "1")
    parameter_object.SetParameter("FixedImagePyramid", "FixedSmoothingImagePyramid")
    parameter_object.SetParameter("MovingImagePyramid", "MovingSmoothingImagePyramid")
    parameter_object.SetParameter("Optimizer", "AdaptiveStochasticGradientDescent")
    parameter_object.SetParameter("HowToCombineTransforms", "Compose")
    parameter_object.SetParameter("Transform", "BSplineTransform")
    parameter_object.SetParameter("Metric", "AdvancedMeanSquares")
    parameter_object.SetParameter("NumberOfHistogramBins", "32")
    parameter_object.SetParameter("FinalGridSpacingInPhysicalUnits", "50.0 50.0")
    parameter_object.SetParameter("NumberOfResolutions", "4")
    parameter_object.SetParameter("AutomaticParameterEstimation", "true")
    parameter_object.SetParameter("ASGDParameterEstimationMethod", "Original")
    parameter_object.SetParameter("MaximumNumberOfIterations", "500")
    parameter_object.SetParameter("MaximumStepLength", "0.1")
    parameter_object.SetParameter("ImagePyramidSchedule", "8 8  4 4  2 2  1 1")
    parameter_object.SetParameter("NumberOfSpatialSamples", "2048")
    parameter_object.SetParameter("NewSamplesEveryIteration", "true")
    parameter_object.SetParameter("CheckNumberOfSamples", "true")
    parameter_object.SetParameter("ErodeMask", "false")
    parameter_object.SetParameter("ErodeFixedMask", "false")
    parameter_object.SetParameter("DefaultPixelValue", "0")
    parameter_object.SetParameter("WriteResultImage", "true")
    parameter_object.SetParameter("ResultImagePixelType", "float")
    parameter_object.SetParameter("ResultImageFormat", "mhd")
    for list_parameters in argv:
        parameter_object.SetParameter(str(list_parameters[0]), str(list_parameters[1]))
    return parameter_object
