import nibabel as nib
import mdreg
import os
import warnings


class Perfusion:
    """
    Generates a perfusion-weighted map from a series of volumes collected with
    alternating label and control acquisitions.

    Attributes
    ----------
    pixel_array : np.ndarray
        The original input pixel array containing interleaved label and control images.
    affine : np.ndarray
        A matrix giving the relationship between voxel coordinates and
        world coordinates.
    moco : bool
        Whether motion correction was applied to the data.
    label : np.ndarray
        The array corresponding to the label images.
    control : np.ndarray
        The array corresponding to the control images.
    mean_label : np.ndarray
        The average of all label images.
    mean_control : np.ndarray
        The average of all control images.
    perfusion_weighted : np.ndarray
        The perfusion-weighted image calculated as mean_label - mean_control.
    deformation_field : np.ndarray
        The deformation field generated by the motion correction process.
        Only available if moco is True.
    """

    def __init__(self, pixel_array, affine, moco=False):
        """Initialize a Perfusion class instance.

        Parameters
        ----------
        pixel_array : np.ndarray
            A multidimensional array containing interleaved label and control images,
            where even indices (0, 2, 4...) correspond to label images and
            odd indices (1, 3, 5...) correspond to control images.
        affine : np.ndarray
            A matrix giving the relationship between voxel coordinates and
            world coordinates.
        moco : bool, optional
            Default False
            If True, motion correction will be applied to the volumes before
            calculating perfusion-weighted images.
        """
        warnings.warn('Perfusion is still a work in progress and likely to '
                      'be re-written. Use with caution.')
        self.pixel_array = pixel_array
        self.affine = affine
        self.moco = moco

        if self.moco:
            self.pixel_array, self.deformation_field, _, _ = mdreg.fit(
                self.pixel_array, force_2d=True)
        self.label = self.pixel_array[..., 0::2]
        self.control = self.pixel_array[..., 1::2]
        if self.label.mean() < self.control.mean():
            warnings.warn("The average signal from the label image is less "
                          "than the average signal from the control image. ")

        self.mean_label = self.label.mean(axis=-1)
        self.mean_control = self.control.mean(axis=-1)
        self.perfusion_weighted = self.mean_label - self.mean_control

    def to_nifti(self, output_directory=os.getcwd(), base_file_name='Output',
                 maps='all'):
        """Exports some of the Perfusion class attributes to NIFTI.

        Parameters
        ----------
        output_directory : string, optional
            Path to the folder where the NIFTI files will be saved.
        base_file_name : string, optional
            Filename of the resulting NIFTI. This code appends the extension.
            Eg., base_file_name = 'Output' will result in 'Output_*.nii.gz'.
        maps : list or 'all', optional
            List of maps to save to NIFTI. This should either be the string "all"
            or a list of maps from ["mean_label", "mean_control", "perfusion_weighted",
            "deformation_field"].
        """
        os.makedirs(output_directory, exist_ok=True)
        base_path = os.path.join(output_directory, base_file_name)
        if maps == 'all' or maps == ['all']:
            maps = ['mean_label', 'mean_control', 'perfusion_weighted',
                    'deformation_field']
        if isinstance(maps, list):
            for result in maps:
                if result == 'mean_label':
                    nifti = nib.Nifti1Image(self.mean_label, self.affine)
                    nib.save(nifti, f"{base_path}_mean_label.nii.gz")
                elif result == 'mean_control':
                    nifti = nib.Nifti1Image(self.mean_control, self.affine)
                    nib.save(nifti, f"{base_path}_mean_control.nii.gz")
                elif result == 'perfusion_weighted':
                    nifti = nib.Nifti1Image(self.perfusion_weighted, self.affine)
                    nib.save(nifti, f"{base_path}_perfusion_weighted.nii.gz")
                elif self.moco is True and result == 'deformation_field':
                    nifti = nib.Nifti1Image(self.deformation_field, self.affine)
                    nib.save(nifti, f"{base_path}_deformation_field.nii.gz")