name: Flake8

on: [pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Run flake8 on your PR - with annotations!
        uses: tayfun/flake8-your-pr@1.0.1